name: test-leaks

on: [push, pull_request]

jobs:
  Test:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:    
    - uses: actions/checkout@v2
    - name: Setup nim
      uses: jiro4989/setup-nim-action@v1
      with:
        nim-version: stable
    - name: Install valgrind
      run: sudo apt-get install -y valgrind
    - name: Test leaks
      shell: bash
      run: |
        nim --version
        cd tests/
        nim c --gc:arc -d:useMalloc test1.nim
        valgrind --leak-check=full ./test1
    
